# Dealing with missing data

## A.  Identifying missing values in tabular data

In [30]:
import pandas as pd
from io import StringIO
import sys

csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

# If you are using Python 2.7, you need
# to convert the string to unicode:

if (sys.version_info < (3, 0)):
    csv_data = unicode(csv_data)

### Step 1: Read the csv file as a pandas dataframe

In [31]:
df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

### Step 2: Check the number of missing values for the columns

In [32]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

### Step 3: access the underlying NumPy array via the `values` attribute

In [33]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

### Step 4: Remove rows from df that contain missing values

In [34]:
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

### Step 5: Remove columns from df that contain missing values

In [35]:
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

### Step 6: Only drop rows where all columns are NaN

In [36]:
df.dropna(how='all') 

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

### Step 7: Drop rows that have less than 3 real values

In [37]:
df.dropna(thresh=3)

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

### Step 8: Only drop rows where NaN appear in specific columns (here: 'C')

In [38]:
df.dropna(subset=['C'])

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

## B. Imputing missing values

In [39]:
# again: our original array
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

### Step 1: impute missing values via the column mean
`from sklearn.impute import SimpleImputer`

`import numpy as np`

In [59]:
from sklearn.impute import SimpleImputer
import numpy as np

myImp = SimpleImputer(missing_values=np.nan, strategy='mean')
imputed_df = myImp.fit_transform(df)
imputed_df

#imp = imp.fit(df.values)
#imputed_data = imp.transform(df.values)
#imputed_data


array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

<br>
<br>